//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comunicador_FacturaTech.FacturaTech {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaWebservice", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaWebservice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLFiscalValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comunicador_FacturaTech.FacturaTech.ArrayOfString MensajeErrorLAYOUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comunicador_FacturaTech.FacturaTech.RespuestaCarvajal MensajeDocumentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comunicador_FacturaTech.FacturaTech.RespuestaCUFE MensajeRespuestaCUFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XMLFiscalValido {
            get {
                return this.XMLFiscalValidoField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLFiscalValidoField, value) != true)) {
                    this.XMLFiscalValidoField = value;
                    this.RaisePropertyChanged("XMLFiscalValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.documentNumberField, value) != true)) {
                    this.documentNumberField = value;
                    this.RaisePropertyChanged("documentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Comunicador_FacturaTech.FacturaTech.ArrayOfString MensajeErrorLAYOUT {
            get {
                return this.MensajeErrorLAYOUTField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorLAYOUTField, value) != true)) {
                    this.MensajeErrorLAYOUTField = value;
                    this.RaisePropertyChanged("MensajeErrorLAYOUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MensajeEmisor {
            get {
                return this.MensajeEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeEmisorField, value) != true)) {
                    this.MensajeEmisorField = value;
                    this.RaisePropertyChanged("MensajeEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaCarvajal MensajeDocumentStatus {
            get {
                return this.MensajeDocumentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeDocumentStatusField, value) != true)) {
                    this.MensajeDocumentStatusField = value;
                    this.RaisePropertyChanged("MensajeDocumentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaCUFE MensajeRespuestaCUFE {
            get {
                return this.MensajeRespuestaCUFEField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaCUFEField, value) != true)) {
                    this.MensajeRespuestaCUFEField = value;
                    this.RaisePropertyChanged("MensajeRespuestaCUFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCarvajal", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaCarvajal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string legalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string businessStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string governmentResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string governmentResponseDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string processName {
            get {
                return this.processNameField;
            }
            set {
                if ((object.ReferenceEquals(this.processNameField, value) != true)) {
                    this.processNameField = value;
                    this.RaisePropertyChanged("processName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string processStatus {
            get {
                return this.processStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.processStatusField, value) != true)) {
                    this.processStatusField = value;
                    this.RaisePropertyChanged("processStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string processDate {
            get {
                return this.processDateField;
            }
            set {
                if ((object.ReferenceEquals(this.processDateField, value) != true)) {
                    this.processDateField = value;
                    this.RaisePropertyChanged("processDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.messageTypeField, value) != true)) {
                    this.messageTypeField = value;
                    this.RaisePropertyChanged("messageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string legalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.legalStatusField, value) != true)) {
                    this.legalStatusField = value;
                    this.RaisePropertyChanged("legalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string businessStatus {
            get {
                return this.businessStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.businessStatusField, value) != true)) {
                    this.businessStatusField = value;
                    this.RaisePropertyChanged("businessStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string governmentResponseCode {
            get {
                return this.governmentResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.governmentResponseCodeField, value) != true)) {
                    this.governmentResponseCodeField = value;
                    this.RaisePropertyChanged("governmentResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string governmentResponseDescription {
            get {
                return this.governmentResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.governmentResponseDescriptionField, value) != true)) {
                    this.governmentResponseDescriptionField = value;
                    this.RaisePropertyChanged("governmentResponseDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCUFE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaCUFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CUFE {
            get {
                return this.CUFEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUFEField, value) != true)) {
                    this.CUFEField = value;
                    this.RaisePropertyChanged("CUFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaGeneral", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string downloadDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string downloadData {
            get {
                return this.downloadDataField;
            }
            set {
                if ((object.ReferenceEquals(this.downloadDataField, value) != true)) {
                    this.downloadDataField = value;
                    this.RaisePropertyChanged("downloadData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaDocumentStatus", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaConsultaDocumentStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comunicador_FacturaTech.FacturaTech.RespuestaCarvajal MensajeDocumentStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaCarvajal MensajeDocumentStatus {
            get {
                return this.MensajeDocumentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeDocumentStatusField, value) != true)) {
                    this.MensajeDocumentStatusField = value;
                    this.RaisePropertyChanged("MensajeDocumentStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacturaTech.WSfacturatechSoap")]
    public interface WSfacturatechSoap {
        
        // CODEGEN: Generating message contract since element name LayOut from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirComprobante", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse EmitirComprobante(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirComprobante", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse> EmitirComprobanteAsync(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name documentNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPDF", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse GenerarPDF(Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse> GenerarPDFAsync(Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest request);
        
        // CODEGEN: Generating message contract since element name documentNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarXML", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse DescargarXML(Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse> DescargarXMLAsync(Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest request);
        
        // CODEGEN: Generating message contract since element name documentID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDocumentStatus", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse ConsultaDocumentStatus(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDocumentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse> ConsultaDocumentStatusAsync(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest request);
        
        // CODEGEN: Generating message contract since element name documentNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarCUFE", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse DescargarCUFE(Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarCUFE", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse> DescargarCUFEAsync(Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest request);
        
        // CODEGEN: Generating message contract since element name documentNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarAcuse", ReplyAction="*")]
        Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse DescargarAcuse(Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarAcuse", ReplyAction="*")]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse> DescargarAcuseAsync(Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirComprobante", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequestBody Body;
        
        public EmitirComprobanteRequest() {
        }
        
        public EmitirComprobanteRequest(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LayOut;
        
        public EmitirComprobanteRequestBody() {
        }
        
        public EmitirComprobanteRequestBody(string LayOut) {
            this.LayOut = LayOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponseBody Body;
        
        public EmitirComprobanteResponse() {
        }
        
        public EmitirComprobanteResponse(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaWebservice EmitirComprobanteResult;
        
        public EmitirComprobanteResponseBody() {
        }
        
        public EmitirComprobanteResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaWebservice EmitirComprobanteResult) {
            this.EmitirComprobanteResult = EmitirComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPDF", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.GenerarPDFRequestBody Body;
        
        public GenerarPDFRequest() {
        }
        
        public GenerarPDFRequest(Comunicador_FacturaTech.FacturaTech.GenerarPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public GenerarPDFRequestBody() {
        }
        
        public GenerarPDFRequestBody(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            this.documentNumber = documentNumber;
            this.companyID = companyID;
            this.acountID = acountID;
            this.documentType = documentType;
            this.Correo = Correo;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.GenerarPDFResponseBody Body;
        
        public GenerarPDFResponse() {
        }
        
        public GenerarPDFResponse(Comunicador_FacturaTech.FacturaTech.GenerarPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral GenerarPDFResult;
        
        public GenerarPDFResponseBody() {
        }
        
        public GenerarPDFResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaGeneral GenerarPDFResult) {
            this.GenerarPDFResult = GenerarPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarXML", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarXMLRequestBody Body;
        
        public DescargarXMLRequest() {
        }
        
        public DescargarXMLRequest(Comunicador_FacturaTech.FacturaTech.DescargarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public DescargarXMLRequestBody() {
        }
        
        public DescargarXMLRequestBody(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            this.documentNumber = documentNumber;
            this.companyID = companyID;
            this.acountID = acountID;
            this.documentType = documentType;
            this.Correo = Correo;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarXMLResponseBody Body;
        
        public DescargarXMLResponse() {
        }
        
        public DescargarXMLResponse(Comunicador_FacturaTech.FacturaTech.DescargarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarXMLResult;
        
        public DescargarXMLResponseBody() {
        }
        
        public DescargarXMLResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarXMLResult) {
            this.DescargarXMLResult = DescargarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDocumentStatus", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequestBody Body;
        
        public ConsultaDocumentStatusRequest() {
        }
        
        public ConsultaDocumentStatusRequest(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDocumentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password;
        
        public ConsultaDocumentStatusRequestBody() {
        }
        
        public ConsultaDocumentStatusRequestBody(string documentID, string companyID, string accountID, string Correo, string Password) {
            this.documentID = documentID;
            this.companyID = companyID;
            this.accountID = accountID;
            this.Correo = Correo;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDocumentStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponseBody Body;
        
        public ConsultaDocumentStatusResponse() {
        }
        
        public ConsultaDocumentStatusResponse(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDocumentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaConsultaDocumentStatus ConsultaDocumentStatusResult;
        
        public ConsultaDocumentStatusResponseBody() {
        }
        
        public ConsultaDocumentStatusResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaConsultaDocumentStatus ConsultaDocumentStatusResult) {
            this.ConsultaDocumentStatusResult = ConsultaDocumentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarCUFERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarCUFE", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarCUFERequestBody Body;
        
        public DescargarCUFERequest() {
        }
        
        public DescargarCUFERequest(Comunicador_FacturaTech.FacturaTech.DescargarCUFERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarCUFERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public DescargarCUFERequestBody() {
        }
        
        public DescargarCUFERequestBody(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            this.documentNumber = documentNumber;
            this.companyID = companyID;
            this.acountID = acountID;
            this.documentType = documentType;
            this.Correo = Correo;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarCUFEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarCUFEResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponseBody Body;
        
        public DescargarCUFEResponse() {
        }
        
        public DescargarCUFEResponse(Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarCUFEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarCUFEResult;
        
        public DescargarCUFEResponseBody() {
        }
        
        public DescargarCUFEResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarCUFEResult) {
            this.DescargarCUFEResult = DescargarCUFEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarAcuseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarAcuse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequestBody Body;
        
        public DescargarAcuseRequest() {
        }
        
        public DescargarAcuseRequest(Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarAcuseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TipoAcuse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        public DescargarAcuseRequestBody() {
        }
        
        public DescargarAcuseRequestBody(string documentNumber, string companyID, string acountID, string documentType, string TipoAcuse, string Correo, string Password) {
            this.documentNumber = documentNumber;
            this.companyID = companyID;
            this.acountID = acountID;
            this.documentType = documentType;
            this.TipoAcuse = TipoAcuse;
            this.Correo = Correo;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DescargarAcuseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DescargarAcuseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponseBody Body;
        
        public DescargarAcuseResponse() {
        }
        
        public DescargarAcuseResponse(Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargarAcuseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarAcuseResult;
        
        public DescargarAcuseResponseBody() {
        }
        
        public DescargarAcuseResponseBody(Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarAcuseResult) {
            this.DescargarAcuseResult = DescargarAcuseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSfacturatechSoapChannel : Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSfacturatechSoapClient : System.ServiceModel.ClientBase<Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap>, Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap {
        
        public WSfacturatechSoapClient() {
        }
        
        public WSfacturatechSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSfacturatechSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSfacturatechSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSfacturatechSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.EmitirComprobante(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest request) {
            return base.Channel.EmitirComprobante(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaWebservice EmitirComprobante(string LayOut) {
            Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest inValue = new Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequestBody();
            inValue.Body.LayOut = LayOut;
            Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).EmitirComprobante(inValue);
            return retVal.Body.EmitirComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.EmitirComprobanteAsync(Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest request) {
            return base.Channel.EmitirComprobanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.EmitirComprobanteResponse> EmitirComprobanteAsync(string LayOut) {
            Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest inValue = new Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.EmitirComprobanteRequestBody();
            inValue.Body.LayOut = LayOut;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).EmitirComprobanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.GenerarPDF(Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest request) {
            return base.Channel.GenerarPDF(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral GenerarPDF(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest inValue = new Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.GenerarPDFRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).GenerarPDF(inValue);
            return retVal.Body.GenerarPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.GenerarPDFAsync(Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest request) {
            return base.Channel.GenerarPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.GenerarPDFResponse> GenerarPDFAsync(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest inValue = new Comunicador_FacturaTech.FacturaTech.GenerarPDFRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.GenerarPDFRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).GenerarPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarXML(Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest request) {
            return base.Channel.DescargarXML(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarXML(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarXMLRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarXML(inValue);
            return retVal.Body.DescargarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarXMLAsync(Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest request) {
            return base.Channel.DescargarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarXMLResponse> DescargarXMLAsync(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarXMLRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarXMLRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.ConsultaDocumentStatus(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest request) {
            return base.Channel.ConsultaDocumentStatus(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaConsultaDocumentStatus ConsultaDocumentStatus(string documentID, string companyID, string accountID, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest inValue = new Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequestBody();
            inValue.Body.documentID = documentID;
            inValue.Body.companyID = companyID;
            inValue.Body.accountID = accountID;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).ConsultaDocumentStatus(inValue);
            return retVal.Body.ConsultaDocumentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.ConsultaDocumentStatusAsync(Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest request) {
            return base.Channel.ConsultaDocumentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusResponse> ConsultaDocumentStatusAsync(string documentID, string companyID, string accountID, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest inValue = new Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.ConsultaDocumentStatusRequestBody();
            inValue.Body.documentID = documentID;
            inValue.Body.companyID = companyID;
            inValue.Body.accountID = accountID;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).ConsultaDocumentStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarCUFE(Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest request) {
            return base.Channel.DescargarCUFE(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarCUFE(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarCUFERequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarCUFE(inValue);
            return retVal.Body.DescargarCUFEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarCUFEAsync(Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest request) {
            return base.Channel.DescargarCUFEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarCUFEResponse> DescargarCUFEAsync(string documentNumber, string companyID, string acountID, string documentType, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarCUFERequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarCUFERequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarCUFEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarAcuse(Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest request) {
            return base.Channel.DescargarAcuse(request);
        }
        
        public Comunicador_FacturaTech.FacturaTech.RespuestaGeneral DescargarAcuse(string documentNumber, string companyID, string acountID, string documentType, string TipoAcuse, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.TipoAcuse = TipoAcuse;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse retVal = ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarAcuse(inValue);
            return retVal.Body.DescargarAcuseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse> Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap.DescargarAcuseAsync(Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest request) {
            return base.Channel.DescargarAcuseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comunicador_FacturaTech.FacturaTech.DescargarAcuseResponse> DescargarAcuseAsync(string documentNumber, string companyID, string acountID, string documentType, string TipoAcuse, string Correo, string Password) {
            Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest inValue = new Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequest();
            inValue.Body = new Comunicador_FacturaTech.FacturaTech.DescargarAcuseRequestBody();
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.companyID = companyID;
            inValue.Body.acountID = acountID;
            inValue.Body.documentType = documentType;
            inValue.Body.TipoAcuse = TipoAcuse;
            inValue.Body.Correo = Correo;
            inValue.Body.Password = Password;
            return ((Comunicador_FacturaTech.FacturaTech.WSfacturatechSoap)(this)).DescargarAcuseAsync(inValue);
        }
    }
}
